CREATE TABLE IF NOT EXISTS test_data (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS riot_accounts (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    puuid TEXT UNIQUE NOT NULL,
    username TEXT NOT NULL,
    tag TEXT NOT NULL,
    region TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    most_recent_loaded_match_end_time BIGINT DEFAULT 1736447460 --Default to Jan 09 2025, start of season 15.
);

CREATE TABLE IF NOT EXISTS bloons_favorite (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    monkey_name TEXT NOT NULL,
    path1 INTEGER NOT NULL,
    path2 INTEGER NOT NULL,
    path3 INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS bloons_key (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    key TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.lol_match_id (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  match_date bigint null,
  match_duration bigint null,
  puuid text not null,
  "matchID" text not null,
  constraint lol_match_id_pkey primary key (id),
  constraint lol_match_id_puuid_fkey foreign KEY (puuid) references riot_accounts (puuid)
) TABLESPACE pg_default;